// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAnawn0iT_M4nu2Y5ZWdaHaBafgYA8owg',
    appId: '1:561836111101:web:4ed0adc2cea95f03c17a94',
    messagingSenderId: '561836111101',
    projectId: 'outty-5b15a',
    authDomain: 'outty-5b15a.firebaseapp.com',
    storageBucket: 'outty-5b15a.firebasestorage.app',
    measurementId: 'G-B98X33HXSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhvmo2zfiNkjFhozbp43ke-Z3d6wpi1XM',
    appId: '1:561836111101:android:d7e2643058d50800c17a94',
    messagingSenderId: '561836111101',
    projectId: 'outty-5b15a',
    storageBucket: 'outty-5b15a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIm116bFNrEk8nssztTLtauVUuXCVd76g',
    appId: '1:561836111101:ios:b9db159de0a9c027c17a94',
    messagingSenderId: '561836111101',
    projectId: 'outty-5b15a',
    storageBucket: 'outty-5b15a.firebasestorage.app',
    iosClientId: '561836111101-doi2amhlr9e54ll3tu38vgi1esfl57fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.outty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIm116bFNrEk8nssztTLtauVUuXCVd76g',
    appId: '1:561836111101:ios:b9db159de0a9c027c17a94',
    messagingSenderId: '561836111101',
    projectId: 'outty-5b15a',
    storageBucket: 'outty-5b15a.firebasestorage.app',
    iosClientId: '561836111101-doi2amhlr9e54ll3tu38vgi1esfl57fp.apps.googleusercontent.com',
    iosBundleId: 'com.example.outty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAnawn0iT_M4nu2Y5ZWdaHaBafgYA8owg',
    appId: '1:561836111101:web:f38e1c8848c01686c17a94',
    messagingSenderId: '561836111101',
    projectId: 'outty-5b15a',
    authDomain: 'outty-5b15a.firebaseapp.com',
    storageBucket: 'outty-5b15a.firebasestorage.app',
    measurementId: 'G-SF9Z7M2YJ3',
  );
}
